### ISSUE TITLE
export also as ESM module

### ISSUE THREAD

**Issue by mojoaxel** [josdejong/propagating-hammerjs#13]
We get the following waning in an Angular project using keychartm (for vis-timeline):

```
WARNING in node_modules/vis-timeline/esnext/esm/vis-timeline-graph2d.js depends on 'propagating-hammerjs'.
CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

It would be helpfull to also export a ESM module.

**Comment by mojoaxel** [comment]
I'll try to look into this issue within the next weeks, but if somebody wants to help, please feel free to do so ;-)

@josdejong Maybe you can label this issue with `Hacktoberfest`!?
(see https://hacktoberfest.digitalocean.com/#maintainers)

**Comment by josdejong** [comment]
> I'll try to look into this issue within the next weeks, but if somebody wants to help, please feel free to do so ;-)

Great thanks Alexander!

> @josdejong Maybe you can label this issue with `Hacktoberfest`!?
> (see https://hacktoberfest.digitalocean.com/#maintainers)

Thanks for the invitation 😄 , I do not have plans to join though.
