### ISSUE TITLE
Way to emit events in test code that is compatible with propagating-hammerjs

### ISSUE THREAD

**Issue by kbullaughey** [josdejong/propagating-hammerjs#2]
I started using `propagating-hammerjs` which works fine for my app but broke my tests. I realized I could fix my failing tests by emitting an additional event before each simulated event with something like the following:

```
hammerInstance.emit('hammer.input', {target: event.target, isFirst: true})
hammerInstance.emit(eventType, event)
```

I'm curious if this is the recommended way to simulate events in a `propagating-hammerjs` compatible way? Or is there a better way to simulate events that will work out of the box? or is there a way that `propagating-hammerjs` could be improved in such a way that the requisite setup for simulated events will have happened without manually needing to do it?

**Comment by josdejong** [comment]
The closer to hammer.js the better. Best would be if this library wouldn't be necessary at all ;).

This is an interesting case, so far I hadn't used `emit` and therefore didn't encounter this issue. I think this problem boils down to the internal property `_firstTarget` not being set in case of an event fired via `emit`. 

I've added some code overriding hammers `emit` event, see https://github.com/josdejong/propagating-hammerjs/commit/ff7b6a750ce4e4be923845d6f52de781b351c23b. Can you check whether this solves the issue?

**Comment by kbullaughey** [comment]
Yes. That fix allowed me to remove the extra `emit()` in my tests.

btw, I was using `emit` in my tests because that's what I saw you doing in your tests. Is this the best way for me to be testing my app's use of hammerjs? I manually create an event object that is an ordinary javascript object (not an `Event`) and fill in the details that hammerjs uses. But this required some trial an error, and inspection of hammerjs's source code to get working. It's also probably rather brittle. It's also not easy to simulate more elaborate gestures. 

Is there a better way to do this? Does hammerjs expose an interface (other than `emit`) that works well for simulating events during tests?

**Comment by josdejong** [comment]
Ok great that it works.

I'm not sure which tests you mean, at least `propagating-hammerjs` doesn't have tests (sorry for that).

**Comment by josdejong** [comment]
I don't know what is the preferred way to test touch events with hammer. I suppose the "right"  way is to create real DOM events and fire them via real DOM event handlers attached to real DOM elements. But that's not so trivial.
