### ISSUE TITLE
Use apply() in stopPropagation wrapper

### ISSUE THREAD

**Issue by rjbriody** [josdejong/propagating-hammerjs#6]
Hello,

I am using vis.js (and consequently propagating-hammerjs) in conjunction with https://github.com/Pomax/react-onclickoutside. I am getting the following error for click events.

Chrome: `Uncaught TypeError: Illegal invocation`
Firefox: `TypeError: 'stopPropagation' called on an object that does not implement interface Event.`

I believe the following line should be changed to 

```
srcStop.apply(event.srcEvent);
```

https://github.com/josdejong/propagating-hammerjs/blob/7cab5b246e6570b006ef0d344e62cee3febd7b64/propagating.js#L204

I didn't bother creating a PR since this is a very minor change.

**Comment by josdejong** [comment]
Thanks, good point. I've fixed it in v1.4.6 by binding the `srcStop` method to `even.srcEvent`.

**Comment by rjbriody** [comment]
Excellent. Thanks for the quick response.

Based on the vis.js package.json, this will be automatically picked up in the next vis.js release. Any idea when that will be?

(Sidenote: I realize that this sort of question probably isn't appropriate for a github issue, but I was unable to find a general forum or message board for vis.js. If one exists, please let me know.)

**Comment by josdejong** [comment]
Yo're welcome. Next release of vis.js will be this week. If you're in a hurry you can always (temporarily) create a built of vis.js yourself.
